name: Build and Deploy
on:
  push:
    branches: [ develop, main ]
  #pull_request:
  #  branches: [ main ]

jobs:

  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - 
      uses: actions/checkout@v2
      name: Check out code
    - 
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: lucasvar/im-bot
        tags: ${{ github.sha }} , latest
        registry: registry.lucasvar.tech
        username: ${{ secrets.DOCKER_USERNAME_K8S }}
        password: ${{ secrets.DOCKER_PASSWORD_K8S }}
    
  deploy-to-cluster:
    name: Deploy to cluster
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
    - 
      name: Deploy to Kubernetes cluster
      uses: steebchen/kubectl@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: set image --record deployment/im-bot im-bot=registry.lucasvar.tech/lucasvar/im-bot:${{ github.sha }}
    - 
      name: Verify deployment
      uses: steebchen/kubectl@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        KUBECTL_VERSION: "1.19"
      with:
        args: '"rollout status deployment/im-bot"'
