name: Build and Deploy

on:
  push:
    branches: [ develop, main ]
  #pull_request:
  #  branches: [ main ]

jobs:

  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - 
      uses: actions/checkout@v2
      name: Check out code
    - 
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: lucasvar/im-bot
        tags: ${{ github.head_ref }}-${{ github.sha }} , latest
        registry: registry.lucasvar.tech
        username: ${{ secrets.DOCKER_USERNAME_K8S }}
        password: ${{ secrets.DOCKER_PASSWORD_K8S }}
    - 
      name: Deploy to Kubernetes cluster
      uses: steebchen/kubectl@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: set image --record deployment/im-bot im-bot=lucasvar/im-bot:${{ github.ref }}-${{ github.sha }}
    - 
      name: Verify deployment
      uses: steebchen/kubectl@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        KUBECTL_VERSION: "1.20"
      with:
        args: '"rollout status deployment/im-bot"'
