name: Docker Image CI

on:
  push:
    branches: [ develop ]
  #pull_request:
  #  branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker build . -t im-bot:$(date +%s)
